### ISSUE TITLE
Lint Staged is not taking the process arguments

### ISSUE THREAD

**Issue by theprantadutta** [hyiso/lint_staged#19]
From the docs,
 --processes [int]                  limit the maximum processes can run at the same time.
 but when I run this with
 dart run lint_staged --process 1
 this throws the following error
 Unhandled exception:
FormatException: Could not find an option named "--processes".
#0      Parser._validate (package:args/src/parser.dart:324:7)
#1      Parser._handleLongOption (package:args/src/parser.dart:310:7)
#2      Parser._parseLongOption (package:args/src/parser.dart:271:12)
#3      Parser.parse (package:args/src/parser.dart:91:11)
#4      ArgParser.parse (package:args/src/arg_parser.dart:334:42)
#5      main (file:///C:/Users/prant/AppData/Local/Pub/Cache/hosted/pub.dev/lint_staged-0.5.1/bin/lint_staged.dart:20:32)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
how can I actually limit the process here?

**Comment by EArminjon** [comment]
Hello @hyiso,

The following PR https://github.com/hyiso/lint_staged/pull/18 is not deployed in pub dev, can you make a release please ?
